In [1]:
from datetime import datetime
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

plt.rcParams.update({"font.size": 12})
%matplotlib inline

In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
In C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\matplotlib\mpl-data\stylelib\_classic_test.mplstyle:
The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

In [2]:
def common_elements(list1,list2,list3=[]):
    users_wsb_stocks = set(list1) & set(list2) 
    print('Elements in List 1:',len(list1))
    print('Elements in List 2:',len(list2))
    print('common_elements [List 1,2]:',len(users_wsb_stocks))
    print('common_elements:',users_wsb_stocks)
    if list3:
      print('Elements in List 3:',len(list3))
      users_wsb_investing = set(list1) & set(list3)
      print('common_elements [List 1,3]:',len(users_wsb_investing))
      print('common_elements:',users_wsb_investing)
      users_stocks_investing = set(list2) & set(list3)
      print('common_elements [List 2,3]:',len(users_stocks_investing))
      print('common_elements:',users_stocks_investing)  
      users = set(list1) & set(list2) & set(list3)
      print('common_elements [List 1,2,3]:',len(users))
      print('common_elements:',users)

In [4]:
#load datasets

wsb_users_25to75 = pd.read_csv('data/WSB_users_25to75.csv',sep=';')
stocks_users_25to75 = pd.read_csv('stocks/data/stocks_users_25to75.csv',sep=';')
investing_users_25to75 = pd.read_csv('investing/data/investing_users_25to75.csv',sep=';')

wsb_users_overall_top = pd.read_csv('data/WSB_users_Overall_top_median.csv',sep=';')
stocks_users_overall_top = pd.read_csv('stocks/data/stocks_users_Overall_top_median.csv',sep=';')
investing_users_overall_top = pd.read_csv('investing/data/investing_users_Overall_top_median.csv',sep=';')

wsb_users_DD_median = pd.read_csv('data/WSB_users_DD_median.csv',sep=';')
stocks_users_DD_median = pd.read_csv('stocks/data/stocks_users_DD_median.csv',sep=';')
investing_users_DD_median = pd.read_csv('investing/data/investing_users_DD_median.csv',sep=';')

In [72]:
# all submissions
wsb = pd.read_csv('data/WSB_data_with_emb.csv',sep=';')
stocks = pd.read_csv('stocks/data/stocks_submissions_all.csv',sep=';')
investing= pd.read_csv('investing/data/investing_submissions_all.csv',sep=';')

C:\Users\96ank\AppData\Local\Continuum\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3326: DtypeWarning: Columns (1,5) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)

In [5]:
## DD users

wsb_dd = pd.read_csv('data/WSB_users_DD.csv',sep=';')
stocks_dd = pd.read_csv('stocks/data/stocks_users_DD.csv',sep=';')
investing_dd = pd.read_csv('investing/data/investing_users_DD.csv',sep=';')

In [6]:
common_elements(wsb_users_25to75['author'].tolist(),stocks_users_25to75['author'].tolist(),investing_users_25to75['author'].tolist())

Elements in List 1: 5440
Elements in List 2: 739
common_elements [List 1,2]: 88
common_elements: {'leadlagreport', 'trackrecordasia', '2019Jamesy', 'Rauf_KB', 'JWKirby', 'TheHolyDollar', 'tsf_peso', 'dhpw2', 'a2options', 'Gabriele25', 'Ituglobal', 'Salty-Amount-2337', 'DoritosHD', 'TheStonksHub', 'Un-Scammable', 'ElitePhoenix-', 'water_boat', 'Start155', 'ilikelucy1', 'Michael12390', 'CIARRAPUNGI', 'thebreadjordan', 'joelivi053', 'automax', 'CoffeeNTrees', 'FakeItThenMakeIt', 'Beginning-Citron-883', 'hockeyfun1', 'hello-world-foo-bar', 'Virtual-Pin1025', 'sparttann', 'Bogashi', 'KingTimKap', 'ukiyuh', 'Red_Icnivad', 'Abhisingh9916', 'diddy41', 'folkwoodswest', 'bearsgotoalaskanstfu', 'learner4f', 'Traditional_Fee_8828', 'repos39', 'WeedKingX', 'JustCantGoTitsUp', 'ThePracticalInvestor', 'clint1reid', 'JKK201519', 'xSathya', 'hhh888hhhh', 'internet_emporium', 'Hard_working247', 'i_love_my_scrotum', 'WhichEdge', 'slow_down_more', 'stillness0072', 'whiteninja123', 'yushey1', 'thedowcast', 'MangoExternal', 'rockwellave', 'NoeticOptions', 'LeadingChallenge2', 'interestingstuff6', 'rawnaldo', 'threefourpizza', '628rand', 'MountainsMan55', 'Stockbaron', 'BenDoverR8Now', 'anteater22', 'badtradesguy', 'ifsksndfhsowo', 'UseAVPNm8', 'PennyStockWorth', 'fustreiche', '_WinnerTakesAll_', 'AdministrativeSail51', 'G23456789', 'Snurtysnurts', 'stanmilc', 'Thetrader2896', 'Slim-JayS', 'Griffin90', 'dreamedaxis', 'QuadraDGoesReddit', 'Pizza_Bagel_', 'JoThePro10', 'flyyoufools97'}
Elements in List 3: 480
common_elements [List 1,3]: 44
common_elements: {'boccherini-trader', '__Player1__', 'lazywizard99', 'folkwoodswest', 'mrfilthynasty4141', 'bearsgotoalaskanstfu', 'kirri008', 'learner4f', 'ilikelucy1', 'CIARRAPUNGI', 'pmor', 'Litquidity88', 'automax', 'NoAbility2435', 'b1ackfyre', 'AmarKS10K', 'jmj_daytrader', 'ChattyChris', 'hhh888hhhh', '007moonboundnxs', 'Hard_working247', 'WhichEdge', 'slow_down_more', 'hello-world-foo-bar', 'ogordained', 'stillness0072', 'Slim-JayS', 'QuasiPinoy', 'GadnukBreakerOfWrlds', 'bragghy', 'investorio', 'diddycarter', 'Griffin90', 'UKARCADIA', 'QuadraDGoesReddit', 'bestzec', 'MrOaiki', 'mfairview', 'TheStonksHub', 'cryptotiks', 'Avid_Hiker98', 'MountainsMan55', 'KingTimKap', 'BenDoverR8Now'}
common_elements [List 2,3]: 73
common_elements: {'dailystockalert', 'Aaronacorona', 'folkwoodswest', 'Greenjuice154', 'luckystock101', 'AIONisMINE', 'bearsgotoalaskanstfu', '036Gooddaysir036', 'StocksHighAlert', 'learner4f', 'cute-girl-in-a-dress', 'depressed333', 'ilikelucy1', 'WouldYouLikeToTouch', 'CIARRAPUNGI', 'Tenesmus83', 'sendokun', 'Yossi25', 'BuyLowSellNever', 'chopsui101', 'Historical_Job_8609', 'mightyduck19', 'zanoo911', 'makaros622', 'PoolsApp', 'NPRjunkieDC', 'automax', 'DarthTrader357', 'The0Walrus', 'moodring88', 'isaac000316', 'Aretetrading_Twitter', 'Virus4762', 'RefinedStrategist', 'zeroskater45', 'TonyLiberty', 'hhh888hhhh', 'Shaun8030', 'manlymatt83', 'BurnerBurnerBurns20', 'r2002', 'vovr', 'Hard_working247', '123wanderlust', 'gohackthat', 'WhichEdge', 'slow_down_more', 'hello-world-foo-bar', 'stillness0072', 'wallstnow1', 'AronwithoneA', 'Slim-JayS', 'Ok-Length1319', 'ProudResident', 'b10m1m1cry', 'kelu213', 'Griffin90', 'abcde123edcba', 'akokaz1', 'usernaame001', 'QuadraDGoesReddit', 'thinkB4WeSpeak', 'NineteenSixtySix', 'VonDerBerg', 'OfficerTruth', 'TheStonksHub', 'joeroganthumbhead', 'MountainsMan55', 'KingTimKap', 'CoffeeQID', 'valuescott', 'BenDoverR8Now', 'Lovedubai37'}
common_elements [List 1,2,3]: 19
common_elements: {'folkwoodswest', 'bearsgotoalaskanstfu', 'learner4f', 'ilikelucy1', 'CIARRAPUNGI', 'automax', 'hhh888hhhh', 'Hard_working247', 'WhichEdge', 'slow_down_more', 'hello-world-foo-bar', 'stillness0072', 'Slim-JayS', 'Griffin90', 'QuadraDGoesReddit', 'TheStonksHub', 'MountainsMan55', 'KingTimKap', 'BenDoverR8Now'}

In [7]:
common_elements(wsb_users_overall_top['author'].tolist(),stocks_users_overall_top['author'].tolist(),investing_users_overall_top['author'].tolist())

Elements in List 1: 3625
Elements in List 2: 493
common_elements [List 1,2]: 56
common_elements: {'follow-spy', 'moazzam0', 'Start155', 'Fargraven', 'E_lonui7xz', 'Horazon99', 'Michael12390', 'thebreadjordan', 'DisastrousBluebirb', 'JustCantGoTitsUp', 'Sir_Meowstro', 'flovidchan', 'techpreneur_13', '0toHeroInvesting', 'ladybaybee', 'notbrokemexican', 'just_lick_my_ass', 'Sirrus_VG', 'RowanHarley', 'nafizzaki', 'seebz69', 'similiarintrests', 'MoarTarriffs', 'rawrtherapybackup', 'professordurian', 'Stocks45', 'AutoModerator', 'internet_emporium', 'civgarth', 'Torlek1', 'Stockbaron', 'TiltMastery', 'imm_uol1819', 'No_Seesaw1134', 'SavienKennedy', 'NightcoreRo', 'hockeyfun1', 'ogordained', 'gms2912', 'Headline123', 'nobjos', 'yushey1', 'swaggymedia', 'onemanstrong', 'rhetorical_twix', 'ramjaz', 'bigbear0083', 'Sweet-Zookeepergame', 'threefourpizza', 'LavenderAutist', 'mfairview', 'TheStonksHub', 'MountainsMan55', 'ukiyuh', 'Red_Icnivad', 'BenDoverR8Now'}
Elements in List 3: 321
common_elements [List 1,3]: 39
common_elements: {'lulzcakes', 'moazzam0', 'kirri008', 'xxx69harambe69xxx', 'Michael12390', 'Dotald_Trump', 'MakeoverBelly', 'mightyduck19', 'Lyman-Zerga', 'ilikepancakez', 'Litquidity88', 'vulcan_on_earth', 'nafizzaki', 'CattleTurdBurgler', 'seebz69', 'rawrtherapybackup', 'Foufou190', 'AutoModerator', 'COMPUTER1313', 'urriola35', 'ogordained', 'NineteenEighty9', 'rawrtherapy', 'potatoandbiscuit', 'QuasiPinoy', 'bragghy', 'whossayn', 'ShaidarHaran2', 'cannainform2', 'jacquesopper', 'Jeroen_Jrn', 'Trowawaycausebanned4', 'Pick2', 'mark000', 'Cygopat', 'GaniB', 'Timelapze', 'squeeeeenis', 'SebastianPatel'}
common_elements [List 2,3]: 36
common_elements: {'moazzam0', 'coolcomfort123', 'markyu007', '3STmotivation', 'luchins', 'Michael12390', 'Tenesmus83', 'Yossi25', 'augustopinochet101', 'Avaronah', 'Nat9523', 'nafizzaki', 'seebz69', 'rawrtherapybackup', 'InterestingNews1', 'Shaun8030', 'AutoModerator', 'manlymatt83', 'ogordained', '01Cloud01', 'BigBet0', 'Maficinc', 'LuxGang', 'AjaxFC1900', 'daynightcase', 'pikindaguy', 'abcde123edcba', 'Okmanl', 'silly321', 'thinkB4WeSpeak', 'hooman_or_whatever', 'QuantalyticsResearch', 'rareliquid', 'luislovesmoney', 'joeroganthumbhead', 'Ironleg01'}
common_elements [List 1,2,3]: 7
common_elements: {'AutoModerator', 'moazzam0', 'ogordained', 'nafizzaki', 'seebz69', 'Michael12390', 'rawrtherapybackup'}

In [8]:
common_elements(wsb_dd['author'].tolist(),stocks_dd['author'].tolist(),investing_dd['author'].tolist())

Elements in List 1: 3486
Elements in List 2: 985
common_elements [List 1,2]: 94
common_elements: {'2019Jamesy', 'Horazon99', 'Rauf_KB', 'mightyduck19', 'techpreneur_13', 'JWKirby', 'tsf_peso', 'Sirrus_VG', 'seebz69', 'a2options', 'ogordained', 'No_Seesaw1134', 'rhetorical_twix', 'ramjaz', 'Salty-Amount-2337', 'LavenderAutist', 'DoritosHD', 'TheStonksHub', 'follow-spy', 'ElitePhoenix-', 'water_boat', 'Start155', 'ilikelucy1', 'CIARRAPUNGI', 'joelivi053', 'CoffeeNTrees', 'AvalieV', 'Beginning-Citron-883', 'TiltMastery', 'Mysterious----', 'SavienKennedy', 'hello-world-foo-bar', 'TwistedFluke', 'maxoptionstrading', 'Virtual-Pin1025', 'sparttann', 'Bogashi', 'KingTimKap', 'ukiyuh', 'Red_Icnivad', 'boccherini-trader', 'diddy41', 'folkwoodswest', 'moazzam0', 'Fargraven', 'bearsgotoalaskanstfu', 'learner4f', 'Traditional_Fee_8828', 'repos39', 'WeedKingX', 'DisastrousBluebirb', 'JustCantGoTitsUp', 'ThePracticalInvestor', 'clint1reid', 'RowanHarley', 'nafizzaki', 'JKK201519', 'internet_emporium', 'Hard_working247', 'imm_uol1819', 'slow_down_more', 'stillness0072', 'whiteninja123', 'yushey1', 'swaggymedia', 'thedowcast', 'NoeticOptions', 'interestingstuff6', 'threefourpizza', 'rawnaldo', 'NineteenSixtySix', '628rand', 'BenDoverR8Now', 'anteater22', '0toHeroInvesting', 'UseAVPNm8', 'PennyStockWorth', 'notbrokemexican', '_WinnerTakesAll_', 'AdministrativeSail51', 'G23456789', 'rawrtherapybackup', 'Stocks45', 'stanmilc', 'Thetrader2896', 'Headline123', 'nobjos', 'myke_oxbig45', 'Slim-JayS', 'bigbear0083', 'dreamedaxis', 'mfairview', 'flyyoufools97', 'flovidchan'}
Elements in List 3: 45
common_elements [List 1,3]: 3
common_elements: {'urriola35', 'ogordained', 'Trowawaycausebanned4'}
common_elements [List 2,3]: 7
common_elements: {'abcde123edcba', 'Griffin90', 'silly321', 'vovr', 'QuantalyticsResearch', 'ogordained', 'luchins'}
common_elements [List 1,2,3]: 1
common_elements: {'ogordained'}

In [9]:
common_elements(wsb_users_DD_median['author'].tolist(),stocks_users_DD_median['author'].tolist(),investing_users_DD_median['author'].tolist())

Elements in List 1: 1746
Elements in List 2: 251
common_elements [List 1,2]: 19
common_elements: {'follow-spy', 'Fargraven', 'DisastrousBluebirb', 'JustCantGoTitsUp', '0toHeroInvesting', 'notbrokemexican', 'RowanHarley', 'rawrtherapybackup', 'internet_emporium', 'imm_uol1819', 'No_Seesaw1134', 'SavienKennedy', 'Headline123', 'rhetorical_twix', 'threefourpizza', 'mfairview', 'ukiyuh', 'Red_Icnivad', 'BenDoverR8Now'}
Elements in List 3: 23
common_elements [List 1,3]: 1
common_elements: {'urriola35'}
common_elements [List 2,3]: 0
common_elements: set()
common_elements [List 1,2,3]: 0
common_elements: set()

In [10]:
wsb_dd[wsb_dd['author'] =='ogordained']

,Unnamed: 0,author,id,title,selftext,date,day,month,year,tickers_,...,title_polarity,title_subjectivity,body_polarity,body_subjectivity,title_tokens,selftext_tokens,polarity,years_count,months_count,dates_count
2942,6117,ogordained,29,"Since there's so many new users here, many may...",Proof is in the tendies but really I just like...,"['2021-02-02', '2021-01-28', '2019-07-20', '20...",2 28 20 6 15 14 13 12 11 8 5 4 31 30 29 28 25 ...,"['2', '1', '7', '4', '2', '2', '2', '2', '2', ...","['2021', '2021', '2019', '2019', '2019', '2019...",NaN,...,0.155195,0.386364,0.030859,0.323512,"['Since', 'there', ""'s"", 'so', 'many', 'new', ...","['Proof', 'is', 'in', 'the', 'tendies', 'but',...",0.186053,"{'2021': 2, '2019': 27}","{'2': 9, '1': 18, '7': 1, '4': 1}","{'2021-02-02': 1, '2021-01-28': 1, '2019-07-20..."

In [ ]:
wsb[wsb['author'] =='ogordained']

In [96]:
wsb.iloc[856396]

Unnamed: 0                                                          856396
created_utc                                            2019-02-08 12:26:22
SegmentID                                                           856396
author                                                          ogordained
id                                                                  aog1db
link_flair_text                                                 Discussion
num_comments                                                            42
score                                                                    1
subreddit_subscribers                                               494912
selftext                 ## UNITED STATES\n\n* **Futures** are down aft...
title                    I Read The News So You Don't Have To - Market ...
upvote_ratio                                                           0.0
embedding                [0.015106662176549435, -0.5883835554122925, -0...
bigram                                               [Market News, Feb. 8]
trigram                                                    [Read The News]
four-gram                                                               []
five-gram                                                               []
year                                                                  2019
Name: 856396, dtype: object

In [97]:
wsb.iloc[856396]['title']

"I Read The News So You Don't Have To - Market News (Feb. 8, 2019)"

In [98]:
wsb.iloc[856396]['selftext']

"## UNITED STATES\n\n* **Futures**\xa0are down after Trump said he would not meet with Xi Jinping to sign a trade deal ahead of the March 1 deadline\n* **Jeff Bezos,** owner of the Washington Post and founder of Amazon.com, accused National Enquirer parent American Media of threatening to release embarrassing photos of him\n   * AMI’s owner is a long-time associate of Donald Trump\n* The **merger of BB&amp;T and SunTrust** will create America's sixth largest bank with $442bn in assets and $342bn in deposits\xa0\n   * The combined bank will have a new name, tbd\xa0\n* **Twitter** posted record quarterly profits but a decline in users sent their shares down 9.8%\n\n## OTHER\n\n* The\xa0**Bank of England**\xa0scrapped plans to gradually to raise interest rates and dramatically cut Britain’s growth forecast\n   * the bank now expects the economy to expand by 1.2% this year; it had recently predicted 1.7%\n   * It gave a one-in-four chance of recession\n* **France**\xa0withdrew its ambassador to\xa0**Italy**\n   * French ministers are furious that Italy’s populist government has shown sympathy with and met the leaders of the\xa0*yellow vests*\xa0protest movement\n   * Italy accused France of continuing African colonialism\n* $20m in\xa0**American aid to Venezuela**\xa0remains stuck at the border with Colombia\n   * Nicolás Maduro’s government continued to refuse relief to his nation\n\n## CHINA\n\n* China is moving ahead with a new class of strategic submarines called SSBNs and may come under pressure to reconsider its long-standing **“no first use” nuclear policy**"

In [12]:
stocks_dd[stocks_dd['author'] =='ogordained']

,Unnamed: 0,author,id,title,selftext,date,day,month,year,tickers_,...,title_polarity,title_subjectivity,body_polarity,body_subjectivity,title_tokens,selftext_tokens,polarity,years_count,months_count,dates_count
802,802,ogordained,22,I Read The News So You Don't Have To -- Market...,## UNITED STATES\n\n* **Futures** point to a m...,"['2019-02-19', '2019-02-15', '2019-02-14', '20...",19 15 14 12 11 8 6 5 4 30 29 25 24 17 16 15 14...,"['2', '2', '2', '2', '2', '2', '2', '2', '2', ...","['2019', '2019', '2019', '2019', '2019', '2019...",NaN,...,0.0,0.0,0.018865,0.3161,"['I', 'Read', 'The', 'News', 'So', 'You', 'Do'...","['#', '#', 'UNITED', 'STATES', '\n\n', '*', '*...",0.018865,{'2019': 22},"{'2': 9, '1': 13}","{'2019-02-19': 1, '2019-02-15': 1, '2019-02-14..."

In [ ]:
stocks[stocks['author'] =='ogordained']

In [109]:
len(set(wsb[wsb['author'] =='ogordained']['title'].tolist()) & set(stocks[stocks['author'] =='ogordained']['title'].tolist()))

17

In [93]:
stocks.iloc[153121]

created_utc                                            2019-02-08 12:26:26
SegmentID                                                           153121
author                                                          ogordained
created_utc.1                                          2019-02-08 12:26:26
id                                                                  aog1e2
link_flair_text                                                       News
num_comments                                                            33
score                                                                    1
subreddit_subscribers                                               321004
selftext                 ## UNITED STATES\n\n* **Futures** are down aft...
title                    I Read The News So You Don't Have To - Market ...
upvote_ratio                                                           0.0
sbert_emb                [0.015106662176549435, -0.5883835554122925, -0...
bigram                                               [Market News, Feb. 8]
trigram                                                    [Read The News]
four-gram                                                               []
five-gram                                                               []
Name: 153121, dtype: object

In [94]:
stocks.iloc[153121]['title']

"I Read The News So You Don't Have To - Market News (Feb. 8, 2019)"

In [95]:
stocks.iloc[153121]['selftext']

"## UNITED STATES\n\n* **Futures**\xa0are down after Trump said he would not meet with Xi Jinping to sign a trade deal ahead of the March 1 deadline\n* **Jeff Bezos,** owner of the Washington Post and founder of Amazon.com, accused National Enquirer parent American Media of threatening to release embarrassing photos of him\n   * AMI’s owner is a long-time associate of Donald Trump\n* The **merger of BB&amp;T and SunTrust** will create America's sixth largest bank with $442bn in assets and $342bn in deposits\xa0\n   * The combined bank will have a new name, tbd\xa0\n* **Twitter** posted record quarterly profits but a decline in users sent their shares down 9.8%\n\n## OTHER\n\n* The\xa0**Bank of England**\xa0scrapped plans to gradually to raise interest rates and dramatically cut Britain’s growth forecast\n   * the bank now expects the economy to expand by 1.2% this year; it had recently predicted 1.7%\n   * It gave a one-in-four chance of recession\n* **France**\xa0withdrew its ambassador to\xa0**Italy**\n   * French ministers are furious that Italy’s populist government has shown sympathy with and met the leaders of the\xa0*yellow vests*\xa0protest movement\n   * Italy accused France of continuing African colonialism\n* $20m in\xa0**American aid to Venezuela**\xa0remains stuck at the border with Colombia\n   * Nicolás Maduro’s government continued to refuse relief to his nation\n\n## CHINA\n\n* China is moving ahead with a new class of strategic submarines called SSBNs and may come under pressure to reconsider its long-standing **“no first use” nuclear policy**"

In [13]:
investing_dd[investing_dd['author'] =='ogordained']

,Unnamed: 0,author,id,title,selftext,date,day,month,year,tickers_,...,title_polarity,title_subjectivity,body_polarity,body_subjectivity,title_tokens,selftext_tokens,polarity,years_count,months_count,dates_count
31,513,ogordained,31,I Read The News So You Don't Have To - Market ...,# UNITED STATES\n\n* **Futures** are pointing ...,"['2018-12-27', '2018-12-21', '2018-12-20', '20...",27 21 20 19 14 11 7 6 3 29 28 20 19 16 15 14 1...,"['12', '12', '12', '12', '12', '12', '12', '12...","['2018', '2018', '2018', '2018', '2018', '2018...",NaN,...,0.5,0.9,0.023004,0.371368,"['I', 'Read', 'The', 'News', 'So', 'You', 'Do'...","['#', 'UNITED', 'STATES', '\n\n', '*', '*', '*...",0.523004,{'2018': 31},"{'12': 9, '11': 15, '10': 5, '8': 1, '7': 1}","{'2018-12-27': 1, '2018-12-21': 1, '2018-12-20..."

In [ ]:
investing[investing['author'] =='ogordained']

In [48]:
wsb_dd.columns

Index(['Unnamed: 0', 'author', 'id', 'title', 'selftext', 'date', 'day',
       'month', 'year', 'tickers_', 'tickers_count_', 'link_flair_text',
       'comments_mean', 'comments_sum', 'score_mean', 'score_sum',
       'upvote_ratio_mean', 'upvote_ratio_sum', 'flairs', 'flairs_count',
       'title_polarity', 'title_subjectivity', 'body_polarity',
       'body_subjectivity', 'title_tokens', 'selftext_tokens', 'polarity',
       'years_count', 'months_count', 'dates_count'],
      dtype='object')

In [73]:
from IPython.display import display

In [147]:
def author_stats(author_name,df1,df2,df3,submission_df1,submission_df2,submission_df3):
    row1 = df1[df1['author'] == author_name]
    row2 = df2[df2['author'] == author_name]
    row3 = df3[df3['author'] == author_name]
    
    df = pd.concat([row1, row2, row3])
    df =df.reset_index()
    df.loc[0,'subreddit'] = 'wsb'
    df.loc[1,'subreddit'] = 'stocks'
    df.loc[2,'subreddit'] = 'investing'
    ## display selected columns
    cols_to_display = ['subreddit','author','dates_count','id','tickers_count_','polarity',
                       'years_count','comments_mean', 'comments_sum','upvote_ratio_mean', 'score_mean', 'score_sum','flairs_count']
    
    df = df.loc[:,cols_to_display]
    
    df = df.rename(columns={"id": "submission_count"})
   
    display(df)
    
    #common posts
    sub1_2 = len(set(submission_df1[submission_df1['author'] ==author_name]['title'].tolist()) & 
                              set(submission_df2[submission_df2['author'] ==author_name]['title'].tolist()))
    sub2_3 = len(set(submission_df2[submission_df2['author'] ==author_name]['title'].tolist()) & 
                              set(submission_df3[submission_df3['author'] ==author_name]['title'].tolist()))
    sub1_3 = len(set(submission_df1[submission_df1['author'] ==author_name]['title'].tolist()) & 
                              set(submission_df3[submission_df3['author'] ==author_name]['title'].tolist()))

    
    #common Tickers
    if((len(eval(df.iloc[0]['tickers_count_']).keys())) > 0) and ((len(eval(df.iloc[1]['tickers_count_']).keys())) > 0) and ((len(eval(df.iloc[2]['tickers_count_']).keys())) > 0):
        if(len(set(eval(df.iloc[0]['tickers_count_']).keys()) & set(eval(df.iloc[1]['tickers_count_']).keys()) & set(eval(df.iloc[2]['tickers_count_']).keys()))>0):
            print('author has posted about atleast one Ticker across all subreddits')
    
    #common years
    
    if(len(set(eval(df.iloc[0]['years_count']).keys()) & set(eval(df.iloc[1]['years_count']).keys()) & set(eval(df.iloc[2]['years_count']).keys()))>0):
        print('author is active across all subreddits')
    else:
        print('author stopped posting in atleast one subreddit')
    
    #display common posts
    print("common posts across subs[WSB,Stocks]:",sub1_2)
    if(sub1_2 > 0):
        if(df.iloc[0]['polarity']> 0) and (df.iloc[1]['polarity']< 0):
            print('author has received positive sentiment in WSB, Negative in Stocks')
        elif(df.iloc[0]['polarity']< 0) and (df.iloc[1]['polarity']> 0):
             print('author has received positive sentiment in Stocks, Negative in WSB')
        else:
            print()
    print("common posts across subs[Stocks,investing]:",sub2_3)
    if(sub2_3 > 0):
        if(df.iloc[1]['polarity']> 0) and (df.iloc[2]['polarity']< 0):
            print('author has received positive sentiment in stocks, Negative in investing')
        elif(df.iloc[1]['polarity']< 0) and (df.iloc[2]['polarity']> 0):
             print('author has received positive sentiment in investing, Negative in stocks')
        else:
             print()
    print("common posts across subs[WSB,investing]:",sub1_3)
    if(sub1_3 > 0):
        if(df.iloc[0]['polarity']> 0) and (df.iloc[2]['polarity']< 0):
            print('author has received positive sentiment in WSB, Negative in investing')
        elif(df.iloc[0]['polarity']< 0) and (df.iloc[2]['polarity']> 0):
             print('author has received positive sentiment in investing, Negative in WSB')
        else:
             print()
    
    print("common posts across all subs:",len(set(submission_df1[submission_df1['author'] ==author_name]['title'].tolist()) & 
                              set(submission_df2[submission_df2['author'] ==author_name]['title'].tolist()) &
                             set(submission_df3[submission_df3['author'] ==author_name]['title'].tolist())))

In [148]:
author_stats('ogordained',wsb_dd,stocks_dd,investing_dd,wsb,stocks,investing)

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,ogordained,"{'2021-02-02': 1, '2021-01-28': 1, '2019-07-20...",29,{},0.186053,"{'2021': 2, '2019': 27}",24.724138,717,0.068966,3.758621,109,"{'DD': 1, 'Discussion': 24, 'Fundamentals': 1,..."
1,stocks,ogordained,"{'2019-02-19': 1, '2019-02-15': 1, '2019-02-14...",22,{},0.018865,{'2019': 22},29.590909,651,0.000000,17.227273,379,"{'News': 20, '': 2}"
2,investing,ogordained,"{'2018-12-27': 1, '2018-12-21': 1, '2018-12-20...",31,{},0.523004,{'2018': 31},66.193548,2052,0.000000,2.129032,66,"{'News': 21, 'Discussion': 1, '': 9}"

author stopped posting in atleast one subreddit
common posts across subs[WSB,Stocks]: 17

common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

In [149]:
# 25to75 percentile common users
common_users= {'folkwoodswest', 'bearsgotoalaskanstfu', 'learner4f', 'ilikelucy1', 'CIARRAPUNGI', 'automax', 'hhh888hhhh', 'Hard_working247', 'WhichEdge', 'slow_down_more',
                  'hello-world-foo-bar', 'stillness0072', 'Slim-JayS', 'Griffin90', 'QuadraDGoesReddit', 'TheStonksHub', 'MountainsMan55', 'KingTimKap', 'BenDoverR8Now'}

for user in list(common_users):
    author_stats(user,wsb_users_25to75,stocks_users_25to75,investing_users_25to75,wsb,stocks,investing)

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,folkwoodswest,"{'2021-07-24': 1, '2021-07-17': 1, '2021-07-14...",34,"{'CLOV': 1, 'AGTC': 1, 'CVAC': 1, 'AAPL': 1, '...",0.321448,"{'2021': 33, '2020': 1}",1.911765,65,0.992647,1.411765,48,"{'Loss': 2, 'DD': 1, 'Technical': 2, 'Analysis..."
1,stocks,folkwoodswest,"{'2021-07-27': 1, '2021-07-17': 1, '2021-07-14...",39,"{'SNDL': 1, 'AAPL': 1, 'MSFT': 1, 'PLTR': 1, '...",0.319461,"{'2021': 21, '2020': 18}",51.794872,2020,1.000000,1.000000,39,"{'Advice': 6, 'Company': 11, 'Analysis': 2, 'D..."
2,investing,folkwoodswest,"{'2021-07-17': 1, '2021-07-14': 1, '2021-05-21...",37,"{'RIOT': 1, 'SPCE': 1, 'AAPL': 1, 'MSFT': 1, '...",0.337112,"{'2021': 19, '2020': 18}",20.081081,743,0.976486,1.081081,40,{'': 37}

author has posted about atleast one Ticker across all subreddits
author is active across all subreddits
common posts across subs[WSB,Stocks]: 1

common posts across subs[Stocks,investing]: 7

common posts across subs[WSB,investing]: 2

common posts across all subs: 1

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,bearsgotoalaskanstfu,"{'2021-10-18': 1, '2021-10-08': 2, '2021-09-28...",16,"{'JMIA': 1, 'PLBY': 1, 'TDUP': 1}",0.148478,"{'2021': 11, '2020': 5}",19.000000,304,0.937500,1.5,24,"{'Discussion': 5, 'News': 4, 'DD': 6, 'Fundame..."
1,stocks,bearsgotoalaskanstfu,"{'2021-11-11': 2, '2021-11-04': 2, '2021-10-26...",15,"{'POSH': 1, 'KPLT': 1, 'TDUP': 1, 'PLBY': 1, '...",0.067032,{'2021': 15},10.266667,154,1.000000,1.0,15,"{'Company': 8, 'Discussion': 4, '': 4, 'News':..."
2,investing,bearsgotoalaskanstfu,"{'2021-11-11': 1, '2021-10-18': 1, '2021-10-08...",17,"{'KPLT': 1, 'TDUP': 1, 'ETSY': 1, 'POSH': 1}",-0.028909,"{'2021': 12, '2020': 5}",16.647059,283,0.882353,1.0,17,{'': 17}

author has posted about atleast one Ticker across all subreddits
author is active across all subreddits
common posts across subs[WSB,Stocks]: 3

common posts across subs[Stocks,investing]: 7
author has received positive sentiment in stocks, Negative in investing
common posts across subs[WSB,investing]: 2
author has received positive sentiment in WSB, Negative in investing
common posts across all subs: 2

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,learner4f,"{'2021-08-25': 2, '2021-03-30': 1, '2021-01-21...",22,{},0.043139,"{'2021': 4, '2020': 18}",30.818182,678,0.958182,2.818182,62,"{'Discussion': 7, 'News': 2, 'DD': 3, 'Shitpos..."
1,stocks,learner4f,"{'2021-08-25': 1, '2021-03-30': 1, '2021-01-21...",14,{},-0.113048,"{'2021': 3, '2020': 11}",50.857143,712,1.000000,1.000000,14,"{'Company': 1, 'News': 4, 'ETFs': 1, 'Ticker':..."
2,investing,learner4f,"{'2021-08-25': 1, '2021-03-30': 1, '2021-01-21...",17,{},0.035909,"{'2021': 3, '2020': 14}",61.058824,1038,1.000000,1.000000,17,{'': 17}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 10
author has received positive sentiment in WSB, Negative in Stocks
common posts across subs[Stocks,investing]: 12
author has received positive sentiment in investing, Negative in stocks
common posts across subs[WSB,investing]: 12

common posts across all subs: 9

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,ilikelucy1,"{'2021-09-13': 1, '2021-06-03': 1, '2021-06-01...",24,{'VET': 1},0.122003,"{'2021': 9, '2020': 15}",329.208333,7901,0.973333,1.083333,26,"{'Discussion': 6, 'DD': 5, 'Meme': 6, 'News': ..."
1,stocks,ilikelucy1,"{'2021-07-28': 1, '2021-06-25': 1, '2021-05-06...",14,{},0.315225,"{'2021': 8, '2020': 6}",114.500000,1603,1.000000,1.000000,14,"{'': 2, 'Company': 2, 'Question': 9, 'Analysis..."
2,investing,ilikelucy1,"{'2021-11-03': 1, '2021-06-28': 1, '2021-01-31...",11,{},0.389136,"{'2021': 3, '2020': 8}",12.727273,140,0.970000,1.000000,11,{'': 11}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 1

common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,CIARRAPUNGI,"{'2020-09-05': 1, '2020-09-01': 3, '2020-08-26...",57,{},0.173794,"{'2020': 50, '2019': 7}",26.192982,1493,0.144386,1.052632,60,"{'Meme': 2, 'Shitpost': 14, 'Discussion': 25, ..."
1,stocks,CIARRAPUNGI,"{'2020-07-11': 1, '2020-06-30': 1, '2020-06-16...",69,{},0.279631,"{'2020': 43, '2019': 26}",15.202899,1049,0.056667,1.115942,77,"{'Question': 44, 'Ticker': 13, 'Discussion': 1..."
2,investing,CIARRAPUNGI,"{'2020-05-25': 1, '2020-05-16': 1, '2020-03-09...",75,{},0.183255,"{'2020': 34, '2019': 41}",19.426667,1457,0.024000,5.573333,418,{'': 75}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 5

common posts across subs[Stocks,investing]: 16

common posts across subs[WSB,investing]: 4

common posts across all subs: 2

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,automax,"{'2021-01-03': 1, '2021-01-01': 1, '2020-12-24...",37,{},0.116743,"{'2021': 2, '2020': 35}",21.216216,785,0.995405,1.324324,49,"{'Chart': 1, 'YOLO': 1, 'Technicals': 4, 'Disc..."
1,stocks,automax,"{'2021-04-16': 1, '2021-02-20': 1, '2021-02-02...",12,{},0.313427,"{'2021': 11, '2020': 1}",6.666667,80,1.000000,1.166667,14,{'': 12}
2,investing,automax,"{'2020-11-16': 1, '2020-10-05': 1, '2020-09-11...",25,{},0.292596,{'2020': 25},23.600000,590,0.965600,1.120000,28,{'': 25}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,hhh888hhhh,"{'2020-06-28': 1, '2020-06-26': 2, '2020-06-23...",35,{},0.188835,"{'2020': 33, '2019': 2}",25.714286,900,0.371429,6.685714,234,"{'Discussion': 19, 'Satire': 1, 'Loss': 1, 'Ga..."
1,stocks,hhh888hhhh,"{'2021-07-08': 1, '2021-05-20': 2, '2021-05-04...",23,{},0.104424,"{'2021': 19, '2020': 4}",102.391304,2355,0.956522,1.043478,24,"{'Advice': 3, 'Company': 6, 'News': 12, 'Indus..."
2,investing,hhh888hhhh,"{'2021-05-04': 1, '2021-04-21': 1, '2021-02-17...",46,{},0.188617,"{'2021': 13, '2020': 33}",67.847826,3121,0.955000,1.152174,53,{'': 46}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 5

common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,Hard_working247,"{'2021-05-27': 2, '2021-05-18': 1, '2021-05-04...",24,{},0.048484,{'2021': 24},19.083333,458,0.987500,1.125000,27,"{'News': 10, 'Discussion': 11, 'Meme': 1, 'Tec..."
1,stocks,Hard_working247,"{'2021-05-18': 1, '2021-05-13': 1, '2021-04-29...",14,{},0.155519,{'2021': 14},61.428571,860,1.000000,1.000000,14,"{'Company': 5, 'Discussion': 1, '': 9, 'News': 4}"
2,investing,Hard_working247,"{'2021-04-15': 2, '2021-04-06': 1, '2021-04-05...",21,{},0.446519,{'2021': 21},30.333333,637,0.988095,1.285714,27,{'': 21}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 1

common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,WhichEdge,"{'2021-10-05': 1, '2021-07-15': 1, '2021-07-01...",37,{},0.047081,"{'2021': 13, '2020': 24}",77.459459,2866,0.982162,1.486486,55,{'Discussion': 37}
1,stocks,WhichEdge,"{'2021-11-04': 1, '2021-07-01': 1, '2021-05-23...",12,{},0.280027,"{'2021': 9, '2020': 3}",28.166667,338,0.805833,1.500000,18,"{'': 8, 'Company': 1, 'Discussion': 3, 'Advice..."
2,investing,WhichEdge,"{'2021-11-04': 1, '2021-07-01': 1, '2021-06-09...",23,{},0.316805,"{'2021': 11, '2020': 12}",12.434783,286,0.869565,1.086957,25,{'': 23}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 1

common posts across subs[Stocks,investing]: 10

common posts across subs[WSB,investing]: 3

common posts across all subs: 1

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,slow_down_more,"{'2021-10-08': 1, '2021-08-19': 1, '2021-08-17...",47,"{'BABA': 1, 'SOS': 1, 'BIDU': 1}",-0.072262,"{'2021': 12, '2020': 35}",33.063830,1554,0.992553,5.510638,259,"{'Meme': 6, 'Loss': 8, 'YOLO': 2, 'Discussion'..."
1,stocks,slow_down_more,"{'2021-02-20': 1, '2021-02-14': 1, '2021-02-11...",22,{'PEP': 1},-0.088453,"{'2021': 3, '2020': 19}",11.681818,257,1.000000,1.045455,23,"{'Company': 3, 'Discussion': 8, 'Question': 11..."
2,investing,slow_down_more,"{'2020-08-25': 2, '2020-08-06': 1, '2020-08-02...",11,{},0.137263,{'2020': 11},14.545455,160,0.727273,1.090909,12,{'': 11}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,hello-world-foo-bar,"{'2021-01-30': 1, '2021-01-29': 2, '2021-01-21...",80,"{'HYLN': 1, 'TECK': 1, 'TSLA': 1, 'AA': 1, 'CL...",0.123190,"{'2021': 11, '2020': 68, '2019': 1}",42.187500,3375,0.323750,1.625000,130,"{'Discussion': 22, 'DD': 9, 'YOLO': 2, 'Shitpo..."
1,stocks,hello-world-foo-bar,"{'2021-01-30': 1, '2021-01-26': 1, '2021-01-23...",18,"{'SEDG': 1, 'X': 1, 'PCG': 1, 'AA': 1, 'GOLD':...",0.110606,"{'2021': 7, '2020': 11}",245.666667,4422,1.000000,1.055556,19,"{'Discussion': 10, '': 8}"
2,investing,hello-world-foo-bar,"{'2021-01-30': 2, '2021-01-26': 1, '2021-01-23...",23,{},0.078049,"{'2021': 6, '2020': 15, '2019': 2}",47.260870,1087,0.652174,1.000000,23,{'': 23}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 4

common posts across subs[Stocks,investing]: 3

common posts across subs[WSB,investing]: 3

common posts across all subs: 1

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,stillness0072,"{'2021-10-08': 2, '2021-09-30': 2, '2021-09-29...",92,"{'MRK': 1, 'CCXI': 1, 'NOK': 1, 'ERIC': 1, 'MI...",0.125900,"{'2021': 81, '2020': 11}",10.793478,993,0.986522,1.945652,179,"{'Discussion': 23, 'News': 28, 'DD': 26, 'Tech..."
1,stocks,stillness0072,"{'2021-11-07': 1, '2021-10-08': 1, '2021-09-30...",42,"{'APT': 1, 'AMC': 1, 'CCXI': 1, 'PFE': 1, 'MIR...",0.111093,"{'2021': 23, '2020': 19}",6.023810,253,0.983571,1.071429,45,"{'Trades': 9, '': 2, 'Company': 7, 'News': 23,..."
2,investing,stillness0072,"{'2021-11-07': 1, '2021-10-08': 1, '2021-09-30...",18,"{'LAKE': 1, 'CCXI': 1, 'MGNX': 1, 'MMM': 1, 'A...",0.148872,"{'2021': 13, '2020': 5}",7.333333,132,1.000000,1.000000,18,{'': 18}

author has posted about atleast one Ticker across all subreddits
author is active across all subreddits
common posts across subs[WSB,Stocks]: 8

common posts across subs[Stocks,investing]: 7

common posts across subs[WSB,investing]: 6

common posts across all subs: 5

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,Slim-JayS,"{'2021-04-09': 1, '2021-04-01': 2, '2021-03-15...",49,"{'CYBN': 1, 'TRIP': 1, 'CMPS': 1}",0.026259,"{'2021': 47, '2020': 2}",3.959184,194,0.949184,2.428571,119,"{'News': 11, 'DD': 13, 'Technical': 1, 'Analys..."
1,stocks,Slim-JayS,"{'2021-08-20': 1, '2021-04-23': 1, '2021-04-22...",15,{},-0.198003,"{'2021': 11, '2020': 4}",0.733333,11,1.000000,1.000000,15,"{'Company': 5, 'News': 4, 'Advice': 6, 'Reques..."
2,investing,Slim-JayS,"{'2021-08-12': 2, '2021-04-19': 2, '2021-03-10...",27,{'CYBN': 1},0.212049,"{'2021': 14, '2020': 13}",3.444444,93,1.000000,1.000000,27,{'': 27}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 1
author has received positive sentiment in investing, Negative in stocks
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,Griffin90,"{'2021-03-05': 1, '2020-08-09': 1, '2020-07-28...",16,{},0.087837,"{'2021': 1, '2020': 12, '2019': 3}",10.3125,165,0.805,1.6875,27,"{'Discussion': 10, 'YOLO': 4, 'Stocks': 1, 'Ga..."
1,stocks,Griffin90,"{'2021-10-25': 1, '2020-12-12': 1, '2020-07-10...",16,{},0.372443,"{'2021': 1, '2020': 7, '2019': 8}",5.9375,95,0.250,1.1250,18,"{'Advice': 5, 'Request': 3, 'Meta': 2, 'Questi..."
2,investing,Griffin90,"{'2020-10-20': 1, '2020-07-29': 1, '2019-08-13...",16,{},0.491600,"{'2020': 2, '2019': 4, '2018': 10}",8.4375,135,0.125,1.5625,25,"{'': 13, 'Help': 2, 'Discussion': 1}"

author is active across all subreddits
common posts across subs[WSB,Stocks]: 2

common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,QuadraDGoesReddit,"{'2020-09-30': 2, '2020-09-08': 3, '2020-09-04...",15,{},0.146688,{'2020': 15},20.466667,307,0.600000,1.0,15,"{'Stocks': 3, 'Shitpost': 6, 'Storytime': 1, '..."
1,stocks,QuadraDGoesReddit,"{'2020-09-04': 1, '2020-09-01': 1, '2020-03-23...",17,{},0.123898,{'2020': 17},24.411765,415,0.117647,1.0,17,"{'': 7, 'Ticker': 6, 'Question': 4, 'Advice': ..."
2,investing,QuadraDGoesReddit,"{'2020-09-08': 2, '2020-09-04': 1, '2020-09-03...",15,{},-0.099086,{'2020': 15},8.800000,132,0.400000,1.0,15,{'': 15}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 1

common posts across subs[Stocks,investing]: 1
author has received positive sentiment in stocks, Negative in investing
common posts across subs[WSB,investing]: 1
author has received positive sentiment in WSB, Negative in investing
common posts across all subs: 1

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,TheStonksHub,"{'2021-10-03': 2, '2021-09-26': 1, '2021-08-29...",12,{},0.347738,{'2021': 12},47.166667,566,0.952500,6.250000,75,{'DD': 12}
1,stocks,TheStonksHub,"{'2021-10-25': 1, '2021-08-29': 1, '2021-08-08...",13,{},0.281890,{'2021': 13},13.000000,169,0.979231,2.076923,27,"{'Company': 13, 'Analysis': 11, 'Discussion': 2}"
2,investing,TheStonksHub,"{'2021-08-29': 1, '2021-08-08': 1, '2021-07-18...",12,{},0.136133,{'2021': 12},18.500000,222,1.000000,1.000000,12,{'': 12}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 7

common posts across subs[Stocks,investing]: 7

common posts across subs[WSB,investing]: 5

common posts across all subs: 5

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,MountainsMan55,"{'2019-10-18': 1, '2019-09-03': 1, '2019-08-21...",14,{},0.012500,{'2019': 14},0.714286,10,0.000000,3.071429,43,"{'': 11, 'Loss': 2, 'Gain': 1}"
1,stocks,MountainsMan55,"{'2021-02-02': 1, '2021-01-24': 1, '2020-10-06...",13,{},-0.008017,"{'2021': 2, '2020': 5, '2019': 6}",0.846154,11,0.461538,1.846154,24,"{'News': 8, '': 5}"
2,investing,MountainsMan55,"{'2021-02-02': 1, '2021-01-24': 1, '2020-10-06...",20,{},0.010030,"{'2021': 2, '2020': 12, '2019': 6}",1.450000,29,0.440500,1.400000,28,{'': 20}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 2
author has received positive sentiment in WSB, Negative in Stocks
common posts across subs[Stocks,investing]: 7
author has received positive sentiment in investing, Negative in stocks
common posts across subs[WSB,investing]: 3

common posts across all subs: 1

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,KingTimKap,"{'2021-09-27': 1, '2021-09-26': 1, '2021-09-24...",50,{},0.291812,"{'2021': 49, '2020': 1}",90.040000,4502,1.00000,1.000000,50,"{'Meme': 10, 'Discussion': 28, 'News': 4, 'DD'..."
1,stocks,KingTimKap,"{'2021-10-11': 1, '2021-09-18': 1, '2021-09-02...",23,{},0.245494,"{'2021': 21, '2020': 2}",14.826087,341,0.98913,1.217391,28,"{'': 5, 'Resources': 1, 'Company': 14, 'Discus..."
2,investing,KingTimKap,"{'2021-10-11': 1, '2021-09-18': 1, '2021-09-09...",23,{},0.265992,"{'2021': 21, '2020': 2}",61.869565,1423,1.00000,1.000000,23,{'': 23}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 12

common posts across subs[Stocks,investing]: 18

common posts across subs[WSB,investing]: 14

common posts across all subs: 12

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,BenDoverR8Now,"{'2021-09-28': 1, '2021-02-02': 2, '2021-01-30...",14,{'BABA': 1},-0.152411,"{'2021': 10, '2020': 4}",94.857143,1328,0.965000,5.571429,78,"{'DD': 5, 'News': 5, 'Discussion': 2, 'Shitpos..."
1,stocks,BenDoverR8Now,"{'2021-11-14': 1, '2021-09-28': 1, '2021-04-29...",17,{},0.224336,"{'2021': 7, '2020': 10}",66.176471,1125,0.987059,1.235294,21,"{'': 11, 'Industry': 1, 'News': 2, 'Advice': 1..."
2,investing,BenDoverR8Now,"{'2021-11-23': 1, '2021-04-15': 1, '2021-03-10...",12,{'TSLA': 1},0.145793,"{'2021': 5, '2020': 7}",91.750000,1101,1.000000,1.000000,12,{'': 12}

author is active across all subreddits
common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 4

common posts across subs[WSB,investing]: 0
common posts across all subs: 0

In [133]:
# overall top common users
common_users= {'AutoModerator', 'moazzam0', 'ogordained', 'nafizzaki', 'seebz69', 'Michael12390', 'rawrtherapybackup'}

for user in list(common_users):
    author_stats(user,wsb_users_overall_top,stocks_users_overall_top,investing_users_overall_top,wsb,stocks,investing)

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,AutoModerator,"{'2021-09-22': 1, '2021-09-21': 1, '2021-04-29...",923,{},0.698890,"{'2021': 84, '2020': 438, '2019': 400, '2018': 1}",14886.398700,13740146,0.409827,113.254605,104534,"{'Daily': 617, 'Discussion': 678, 'Weekend': 3..."
1,stocks,AutoModerator,"{'2021-11-26': 2, '2021-11-25': 2, '2021-11-24...",914,{},0.085446,"{'2021': 511, '2020': 202, '2019': 200, '2018'...",325.949672,297918,0.697341,3.518600,3216,"{'': 824, 'Ticker': 90, 'Discussion': 90}"
2,investing,AutoModerator,"{'2021-11-26': 2, '2021-11-25': 2, '2021-11-24...",1454,{},0.096941,"{'2021': 558, '2020': 293, '2019': 257, '2018'...",139.651307,203053,0.516362,4.351444,6327,{'': 1454}

common posts across subs[WSB,Stocks]: 0
common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,moazzam0,"{'2021-10-07': 1, '2021-10-03': 1, '2021-09-27...",89,"{'BB': 1, 'UTZ': 1, 'GME': 1, 'KHC': 1, 'FB': ...",0.108269,"{'2021': 63, '2020': 26}",90.089888,8018,0.909775,651.696629,58001,"{'Technical': 1, 'Analysis': 1, 'News': 2, 'DD..."
1,stocks,moazzam0,"{'2021-09-27': 2, '2021-02-27': 1, '2021-02-20...",13,"{'BHC': 1, 'KHC': 1, 'GME': 1}",0.020211,"{'2021': 10, '2020': 3}",32.769231,426,0.956923,18.307692,238,"{'Company': 4, 'Analysis': 3, 'News': 1, 'ETFs..."
2,investing,moazzam0,"{'2021-11-06': 1, '2021-09-27': 1, '2021-09-26...",24,"{'BHC': 1, 'GME': 1, 'KHC': 1}",0.115464,"{'2021': 10, '2020': 14}",49.791667,1195,0.909583,128.708333,3089,{'': 24}

common posts across subs[WSB,Stocks]: 4

common posts across subs[Stocks,investing]: 5

common posts across subs[WSB,investing]: 5

common posts across all subs: 3

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,ogordained,"{'2021-02-02': 1, '2021-01-28': 1, '2019-07-20...",29,{},0.186053,"{'2021': 2, '2019': 27}",24.724138,717,0.068966,3.758621,109,"{'DD': 1, 'Discussion': 24, 'Fundamentals': 1,..."
1,stocks,ogordained,"{'2019-02-19': 1, '2019-02-15': 1, '2019-02-14...",22,{},0.018865,{'2019': 22},29.590909,651,0.000000,17.227273,379,"{'News': 20, '': 2}"
2,investing,ogordained,"{'2018-12-27': 1, '2018-12-21': 1, '2018-12-20...",31,{},0.523004,{'2018': 31},66.193548,2052,0.000000,2.129032,66,"{'News': 21, 'Discussion': 1, '': 9}"

common posts across subs[WSB,Stocks]: 17

common posts across subs[Stocks,investing]: 0
common posts across subs[WSB,investing]: 0
common posts across all subs: 0

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,nafizzaki,"{'2021-10-08': 1, '2021-09-23': 1, '2021-09-20...",71,{},0.149528,"{'2021': 36, '2020': 35}",44.380282,3151,0.991268,12.774648,907,"{'News': 7, 'DD': 9, 'Discussion': 35, 'Chart'..."
1,stocks,nafizzaki,"{'2021-04-07': 2, '2021-02-27': 1, '2021-02-26...",12,{'AZN': 1},0.110903,"{'2021': 5, '2020': 7}",13.666667,164,0.898333,17.750000,213,"{'': 3, 'Industry': 1, 'Discussion': 8, 'Off-T..."
2,investing,nafizzaki,"{'2021-11-02': 1, '2021-09-23': 1, '2021-07-24...",23,{'AZN': 1},0.195630,"{'2021': 11, '2020': 12}",45.869565,1055,0.989130,3.782609,87,{'': 23}

common posts across subs[WSB,Stocks]: 2

common posts across subs[Stocks,investing]: 1

common posts across subs[WSB,investing]: 2

common posts across all subs: 1

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,seebz69,"{'2021-10-05': 1, '2021-06-29': 1, '2021-06-25...",42,"{'CRON': 1, 'TLRY': 1}",0.234110,"{'2021': 28, '2020': 10, '2019': 4}",70.452381,2959,0.779048,18.214286,765,"{'News': 3, 'DD': 19, 'Gain': 9, 'Meme': 1, 'D..."
1,stocks,seebz69,"{'2021-07-22': 1, '2021-02-26': 1, '2021-02-25...",13,{'CRON': 1},0.266957,{'2021': 13},10.846154,141,0.928462,9.923077,129,"{'Company': 10, 'Analysis': 4, 'News': 3, 'Dis..."
2,investing,seebz69,"{'2021-03-03': 1, '2021-02-26': 1, '2021-02-25...",14,"{'SNDL': 1, 'CRON': 1, 'ACB': 1}",0.187382,{'2021': 14},68.857143,964,0.942143,44.714286,626,{'': 14}

common posts across subs[WSB,Stocks]: 8

common posts across subs[Stocks,investing]: 4

common posts across subs[WSB,investing]: 3

common posts across all subs: 2

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,Michael12390,"{'2021-03-16': 1, '2021-03-10': 4, '2021-02-18...",59,{'GME': 1},0.053157,"{'2021': 23, '2020': 34, '2019': 1, '2018': 1}",31.033898,1831,0.725763,4.983051,294,"{'Meme': 6, 'Technical': 3, 'Analysis': 3, 'Lo..."
1,stocks,Michael12390,"{'2021-07-28': 1, '2021-05-17': 1, '2021-04-22...",33,{},0.298462,"{'2021': 4, '2020': 26, '2019': 3}",42.121212,1390,0.843939,1.242424,41,"{'Company': 3, 'Question': 10, 'News': 14, '':..."
2,investing,Michael12390,"{'2021-08-16': 1, '2021-05-17': 3, '2021-04-22...",49,{},0.337387,"{'2021': 8, '2020': 40, '2019': 1}",140.755102,6897,0.451633,45.755102,2242,"{'': 48, 'Help': 1}"

common posts across subs[WSB,Stocks]: 6

common posts across subs[Stocks,investing]: 10

common posts across subs[WSB,investing]: 8

common posts across all subs: 3

,subreddit,author,dates_count,submission_count,tickers_count_,polarity,years_count,comments_mean,comments_sum,upvote_ratio_mean,score_mean,score_sum,flairs_count
0,wsb,rawrtherapybackup,"{'2021-09-21': 1, '2021-09-20': 1, '2021-09-17...",30,"{'RKT': 1, 'GME': 1}",0.082451,"{'2021': 24, '2020': 6}",15.433333,463,0.994667,2.700000,81,"{'Discussion': 12, 'DD': 8, 'News': 1, 'Techni..."
1,stocks,rawrtherapybackup,"{'2021-09-17': 1, '2021-08-04': 1, '2021-07-06...",11,{},0.196838,"{'2021': 7, '2020': 4}",110.272727,1213,0.993636,147.454545,1622,"{'Advice': 2, 'Industry': 1, 'Discussion': 2, ..."
2,investing,rawrtherapybackup,"{'2021-10-08': 1, '2021-09-19': 1, '2021-09-17...",31,{},0.107402,"{'2021': 26, '2020': 5}",72.161290,2237,0.985484,33.774194,1047,{'': 31}

common posts across subs[WSB,Stocks]: 1

common posts across subs[Stocks,investing]: 1

common posts across subs[WSB,investing]: 2

common posts across all subs: 0